### example of one neural

In [15]:
import tensorflow as tf
w = tf.Variable(tf.constant(5, dtype=tf.float32))  # set w=5 as initial
# all variable and function:fixed
lr = 0.2  # learning ratio
epoch = 20
for i in range(epoch):  # 40 epoch 
    with tf.GradientTape() as g:  # use with to get gradient
        # g.watch(w) have been done
        loss = tf.square(w + 1) # loss = (w+1)^2
    grads = g.gradient(loss, w)  # .gradient function

    w.assign_sub(lr * grads)  # .assign_sub ：w -= lr*grads, w = w - lr*grads
    print("After %s epoch,w is %f,loss is %f" % (i, w.numpy(), loss))


After 0 epoch,w is 2.600000,loss is 36.000000
After 1 epoch,w is 1.160000,loss is 12.959999
After 2 epoch,w is 0.296000,loss is 4.665599
After 3 epoch,w is -0.222400,loss is 1.679616
After 4 epoch,w is -0.533440,loss is 0.604662
After 5 epoch,w is -0.720064,loss is 0.217678
After 6 epoch,w is -0.832038,loss is 0.078364
After 7 epoch,w is -0.899223,loss is 0.028211
After 8 epoch,w is -0.939534,loss is 0.010156
After 9 epoch,w is -0.963720,loss is 0.003656
After 10 epoch,w is -0.978232,loss is 0.001316
After 11 epoch,w is -0.986939,loss is 0.000474
After 12 epoch,w is -0.992164,loss is 0.000171
After 13 epoch,w is -0.995298,loss is 0.000061
After 14 epoch,w is -0.997179,loss is 0.000022
After 15 epoch,w is -0.998307,loss is 0.000008
After 16 epoch,w is -0.998984,loss is 0.000003
After 17 epoch,w is -0.999391,loss is 0.000001
After 18 epoch,w is -0.999634,loss is 0.000000
After 19 epoch,w is -0.999781,loss is 0.000000


### creat tensor(just like array, list)
also, convert it to np

In [16]:
a = tf.constant([1, 5], dtype=tf.int64)  # create tensor with different dimension
# same as list or array
print("a:", a)
print("a.type:", a.dtype)
print("a.shape:", a.shape)

a: tf.Tensor([1 5], shape=(2,), dtype=int64)
a.type: <dtype: 'int64'>
a.shape: (2,)


In [17]:
import numpy as np
# np to tensor!
a = np.arange(0, 5)
b = tf.convert_to_tensor(a, dtype=tf.int64)
print("a:", a)
print("b:", b)

a: [0 1 2 3 4]
b: tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


In [18]:
# fill with number
import tensorflow as tf
a = tf.zeros([2, 3])  # 2*3 dimension
b = tf.ones(4)
c = tf.fill([2, 2], 9.0)  # fill with 9 c= tf.fill([a*b],n)!!!
print("a:", a)
print("b:", b)
print("c:", c)

a: tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
b: tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
c: tf.Tensor(
[[9. 9.]
 [9. 9.]], shape=(2, 2), dtype=float32)


### use tf.random to create tensor

In [19]:
#normalize
tf.random.set_seed(5)
d = tf.random.normal([2, 2], mean=0.5, stddev=1)
print("d:", d)
# ensure inside some value
# more centralized
e = tf.random.truncated_normal([2, 2], mean=0.5, stddev=1)  # ensure inside 2*stddev
print("e:", e)

d: tf.Tensor(
[[ 0.31969333 -0.45028627]
 [ 0.4603595  -0.2425406 ]], shape=(2, 2), dtype=float32)
e: tf.Tensor(
[[0.72652864 1.3106554 ]
 [1.2466094  1.2749703 ]], shape=(2, 2), dtype=float32)


In [20]:
# use uniform, all same possibility beteen min-max
f = tf.random.uniform([2, 2], minval=0, maxval=1)
print("f:", f)

f: tf.Tensor(
[[0.20179546 0.34707117]
 [0.05555022 0.44125605]], shape=(2, 2), dtype=float32)


### functions
axis =0 : col, axi=1: row 

In [21]:
# cast max min
import tensorflow as tf
x1 = tf.constant([1., 2., 3.], dtype=tf.float64)
print("x1:", x1)
x2 = tf.cast(x1, tf.int32) # float to int
print("x2", x2)
# get max min
print("minimum of x2:", tf.reduce_min(x2))
print("maxmum of x2:", tf.reduce_max(x2))

x1: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
x2 tf.Tensor([1 2 3], shape=(3,), dtype=int32)
minimum of x2: tf.Tensor(1, shape=(), dtype=int32)
maxmum of x2: tf.Tensor(3, shape=(), dtype=int32)


In [22]:
# mean, sum, axis!!!
import tensorflow as tf
x = tf.constant([[1, 2, 3], [2, 2, 3]])
print("x:", x)
print("mean of x:", tf.reduce_mean(x))  # get average
print("sum of x:", tf.reduce_sum(x, axis=1))  # get sum of column
print("sum of x:", tf.reduce_max(x, axis=0))  # get sum of row


x: tf.Tensor(
[[1 2 3]
 [2 2 3]], shape=(2, 3), dtype=int32)
mean of x: tf.Tensor(2, shape=(), dtype=int32)
sum of x: tf.Tensor([6 7], shape=(2,), dtype=int32)
sum of x: tf.Tensor([2 2 3], shape=(3,), dtype=int32)


### tf.Variable: means this is to be trained, mark it
update when trace back

In [23]:
import tensorflow as tf
w = tf.Variable(tf.random.normal([2,3],mean =0,dtype=1))  # set w=5 as initial
print(w)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.03700283,  0.34592864, -0.41550454],
       [-0.47053525,  0.5453562 , -0.7437    ]], dtype=float32)>


### math

In [24]:
w = tf.Variable(tf.constant(1.0))  # set w=5 as init
print(w)
print(w.assign_sub(2) )

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=-1.0>


In [25]:
import tensorflow as tf
a = tf.ones([1, 3])
b = tf.fill([1, 3], 3.)
print("a:", a)
print("b:", b)
print("a+b:", tf.add(a, b))
print("a-b:", tf.subtract(a, b))
print("a*b:", tf.multiply(a, b))
print("b/a:", tf.divide(b, a))
a = tf.fill([1, 2], 3.)
print("a:", a)
print( tf.pow(a, 3))
print(tf.square(a))
print(tf.sqrt(a))


a: tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)
b: tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
a+b: tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float32)
a-b: tf.Tensor([[-2. -2. -2.]], shape=(1, 3), dtype=float32)
a*b: tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
b/a: tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
a: tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)
tf.Tensor([[27. 27.]], shape=(1, 2), dtype=float32)
tf.Tensor([[9. 9.]], shape=(1, 2), dtype=float32)
tf.Tensor([[1.7320508 1.7320508]], shape=(1, 2), dtype=float32)


### multiplication of two Matrix -> important

In [26]:
import tensorflow as tf
a = tf.ones([3, 2])
b = tf.fill([2, 3], 3.)
print("a:", a)
print("b:", b)
print("a*b:", tf.matmul(a, b))

a: tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
b: tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32)
a*b: tf.Tensor(
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]], shape=(3, 3), dtype=float32)


### match lable with data

In [27]:
import tensorflow as tf
features = tf.constant([12, 23, 10, 17])
labels = tf.constant([0, 1, 1, 0])
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
for element in dataset:
    print(element)

(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=23>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=17>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


### get gradient

In [28]:
import tensorflow as tf
x = tf.Variable(tf.constant(3.0))
with tf.GradientTape() as tape:
    y = tf.pow(x, 2)
grad = tape.gradient(y, x)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


### enum

In [29]:
seq = ['one', 'two', 'three']
for i,element in enumerate(seq):
    print(i,element)
for element in enumerate(seq):
    print(element)

0 one
1 two
2 three
(0, 'one')
(1, 'two')
(2, 'three')


### use one-hot --> used as lable

In [30]:
import tensorflow as tf
classes = 4
labels = tf.constant([1, 0, 2,3,2,0])  # min:0, max:2
output = tf.one_hot(labels, depth=classes)
print("result of labels1:", output)
print("\n")

result of labels1: tf.Tensor(
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]], shape=(6, 4), dtype=float32)




### nn.softmax for one-hot, possibility
make the sum of possiblity:1

In [31]:
import tensorflow as tf
x1 = tf.constant([[5.8, 4.0, 1.2, 0.2]])  # 5.8,4.0,1.2,0.2（0）
w1 = tf.constant([[-0.8, -0.34, -1.4],
                  [0.6, 1.3, 0.25],
                  [0.5, 1.45, 0.9],
                  [0.65, 0.7, -1.2]])
b1 = tf.constant([2.52, -3.1, 5.62])
y = tf.matmul(x1, w1) + b1

print("x1.shape:", x1.shape)
print("w1.shape:", w1.shape)
print("b1.shape:", b1.shape)
print("y.shape:", y.shape)
print("y:", y)
# y-> possibility
y_dim = tf.squeeze(y)  
y_pro = tf.nn.softmax(y_dim)  
print("y_dim:", y_dim)
print("y_pro:", y_pro)

x1.shape: (1, 4)
w1.shape: (4, 3)
b1.shape: (3,)
y.shape: (1, 3)
y: tf.Tensor([[ 1.0099998   2.008      -0.65999985]], shape=(1, 3), dtype=float32)
y_dim: tf.Tensor([ 1.0099998   2.008      -0.65999985], shape=(3,), dtype=float32)
y_pro: tf.Tensor([0.2563381  0.69540703 0.04825491], shape=(3,), dtype=float32)


In [32]:
import tensorflow as tf
y = tf.constant([1.01, 2.01, -0.66])
y_pro = tf.nn.softmax(y)
print("After softmax, y_pro is:", y_pro)  # y_pro-> possibility
print("The sum of y_pro:", tf.reduce_sum(y_pro))  # sum ->1

After softmax, y_pro is: tf.Tensor([0.25598174 0.69583046 0.04818781], shape=(3,), dtype=float32)
The sum of y_pro: tf.Tensor(1.0, shape=(), dtype=float32)


### self-update
for variable

In [33]:
import tensorflow as tf
x = tf.Variable(4)
x.assign_sub(1)
print("x:", x)  # 4-1=3

x: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


### get index of max,min 

In [34]:
import numpy as np
import tensorflow as tf
test = np.array([[1, 2, 3], [2, 3, 4], [5, 4, 3], [8, 7, 2]])
print("test:\n", test)
print("index of max for each column", tf.argmax(test, axis=0))  


test:
 [[1 2 3]
 [2 3 4]
 [5 4 3]
 [8 7 2]]
index of max for each column tf.Tensor([3 3 1], shape=(3,), dtype=int64)


### read data true example
iris as example

In [35]:
from sklearn import datasets
from pandas import DataFrame
import pandas as pd
x_data = datasets.load_iris().data  # .data-> features
y_data = datasets.load_iris().target  # .target-> lable
# give index and name
# transfer list into table
x_data = DataFrame(x_data, columns=['feature1', '2', '3', '4']) # add lable
pd.set_option('display.unicode.east_asian_width', True)  
print("x_data add index: \n", x_data)
# add one into table with new name
x_data['lable'] = y_data  # add one column: lable
print("x_data add a column: \n", x_data)

x_data add index: 
      feature1    2    3    4
0         5.1  3.5  1.4  0.2
1         4.9  3.0  1.4  0.2
2         4.7  3.2  1.3  0.2
3         4.6  3.1  1.5  0.2
4         5.0  3.6  1.4  0.2
..        ...  ...  ...  ...
145       6.7  3.0  5.2  2.3
146       6.3  2.5  5.0  1.9
147       6.5  3.0  5.2  2.0
148       6.2  3.4  5.4  2.3
149       5.9  3.0  5.1  1.8

[150 rows x 4 columns]
x_data add a column: 
      feature1    2    3    4  lable
0         5.1  3.5  1.4  0.2      0
1         4.9  3.0  1.4  0.2      0
2         4.7  3.2  1.3  0.2      0
3         4.6  3.1  1.5  0.2      0
4         5.0  3.6  1.4  0.2      0
..        ...  ...  ...  ...    ...
145       6.7  3.0  5.2  2.3      2
146       6.3  2.5  5.0  1.9      2
147       6.5  3.0  5.2  2.0      2
148       6.2  3.4  5.4  2.3      2
149       5.9  3.0  5.1  1.8      2

[150 rows x 5 columns]
